name: attandance_face_recognation
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  dotted_border: ^2.1.0
  camera: ^0.11.0+2
  geolocator: ^13.0.2
  geocoding: ^3.0.0
  intl: ^0.20.1
  lottie: ^3.3.1
  google_mlkit_face_detection: ^0.12.0
  cloud_firestore: ^5.6.1
  firebase_core: ^3.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
